# Generated by Django 5.2.6 on 2025-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_member_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(default='Sin membresía', max_length=50),
        ),
    ]
