# Generated by Django 5.2.6 on 2025-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_rename_name_member_full_name_member_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cedula',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
